import json
from pathlib import Path

from shipgrade.badge import write_badge
from shipgrade.demo.report import make_demo_report
from shipgrade.scoring import compute_score

# The committed launch-evidence badge (spec 5.10): shipgrade grading its own demo. The
# README lead badge points here, so it must always equal the demo's own F/13 score.
COMMITTED_BADGE = Path(__file__).resolve().parents[1] / "docs" / "badge.json"

# The committed illustrative clean-pass badge (spec 5.10): the A a zero-finding, full-coverage
# run produces, generated by the real code path and drift-locked. A reference, not a self-grade.
COMMITTED_CLEAN_BADGE = Path(__file__).resolve().parents[1] / "docs" / "badge-clean.json"


def test_committed_badge_matches_demo_score(tmp_path):
    # Drift guard: regenerate the badge from the demo score via the real code path into
    # tmp_path (never the repo), then assert the committed docs/badge.json equals it. If the
    # demo score changes and docs/badge.json is not regenerated, this fails.
    expected = write_badge(make_demo_report().score, path=str(tmp_path / "badge.json"))
    committed = json.loads(COMMITTED_BADGE.read_text(encoding="utf-8"))
    assert committed == expected


def test_committed_badge_is_the_failing_demo_grade():
    # The launch badge shows the demo's real F/red, not a self-awarded green A. shipgrade
    # audits its own demo honestly.
    committed = json.loads(COMMITTED_BADGE.read_text(encoding="utf-8"))
    assert committed["message"] == "F"
    assert committed["color"] == "red"


def test_readme_user_badge_links_to_the_users_own_report():
    # F-01: the badge a user pastes must link to their own committed report, not a path that
    # exists only in shipgrade's repo.
    readme = (Path(__file__).resolve().parents[1] / "README.md").read_text(encoding="utf-8")
    user_badge_lines = [ln for ln in readme.splitlines() if "<owner>/<repo>" in ln]
    assert user_badge_lines
    for ln in user_badge_lines:
        assert "examples/sample-report.html" not in ln
        assert "(shipgrade-report.html)" in ln


def test_committed_clean_badge_matches_clean_pass_score(tmp_path):
    # The A badge is generated from a zero-finding, full-coverage score, never hand-written
    # (spec 5.10, spec 11 first screen). Paired with the demo F, it shows the scale discriminates.
    clean = compute_score(
        [],
        probes_total=26,
        probes_passed=26,
        probes_failed=0,
        probes_errored=0,
        probes_skipped=0,
    )
    expected = write_badge(clean, path=str(tmp_path / "badge-clean.json"))
    committed = json.loads(COMMITTED_CLEAN_BADGE.read_text(encoding="utf-8"))
    assert committed == expected
    assert committed["message"] == "A"
    assert committed["color"] == "brightgreen"
